### ISSUE TITLE
Support for sucker_punch?

### ISSUE THREAD

**Issue by fwl** [appsignal/appsignal#29]
Hi there!

Are you planning to add support for [sucker_punch](https://github.com/brandonhilkert/sucker_punch)? Quite a lot of people use it for sending emails and performing non-critical jobs.

Thank you.

**Comment by matsimitsu** [comment]
Hi fwl,

We hadn't planned support for sucker punch as of yet. It does seem like a good idea to support it. 
I'll see if I can make time to add support. If you need it yesterday, maybe you can alias `perform` as done here in the sequel support: https://github.com/appsignal/appsignal/blob/master/lib/appsignal/integrations/sequel.rb

**Comment by fwl** [comment]
@matsimitsu thank you for the detailed response :-)

**Comment by appletonwebb** [comment]
Hi, any updates on this feature request by any chance?

**Comment by matsimitsu** [comment]
I don't think we'll be able to support it in the gem. SuckerPunch doesn't have any hooks we can use to wrap a job in AppSignal.

## Option one:
I did play around with it today, and the following code works with minimal impact when using Rails and Ruby 2.0+.

```ruby
# In an intializer: (config/initializers/job_monitor.rb)
module JobMonitor
  extend ActiveSupport::Concern
  included do
    proxy = Module.new do
      define_method(:perform) do |*args|
         Appsignal.monitor_transaction(
          'perform_job.sucker_punch',
          :class  => self.class.to_s,
          :method => 'perform'
        ) do
          super *args
        end
      end
    end
    self.prepend proxy
  end
end

#In your job include `JobMonitor` 
class SingleJob
  include SuckerPunch::Job
  include JobMonitor
  workers 4

  def perform
    STORE << Time.now
  end
end
```

## Option two:
Other options are creating a base class that defines perform and uses `Appsignal.monitor_transaction` to wrap a different method.

```ruby

class MonitoredJob
  def perform
     Appsignal.monitor_transaction(
      'perform_job.sucker_punch',
      :class  => self.class.to_s,
      :method => 'perform'
    ) do
      perform_monitored
    end
  end
end

class SingleJob < MonitoredJob
  include SuckerPunch::Job
  workers 4

  def perform_monitored
    STORE << Time.now
  end
end

```

## Option three
Or, just wrap it in `Appsignal.monitor_transaction` in the job itself:

```ruby
class SingleJob
  include SuckerPunch::Job
  workers 4

  def perform
    Appsignal.monitor_transaction(
      'perform_job.sucker_punch',
      :class  => self.class.to_s,
      :method => 'perform'
    ) do
      STORE << Time.now
    end
  end
end
```

**Comment by fwl** [comment]
@matsimitsu amazing answer, thank you so much!
