### ISSUE TITLE
Support for catching errors in Rake tasks

### ISSUE THREAD

**Issue by tijmenb** [appsignal/appsignal#32]
Is there an acceptable way to make sure exceptions get automatically reported from Rake tasks?

Got a little burned recently, so I now have this horrific monkey patch in my Rakefile.

```ruby 
# Rakefile
require File.expand_path('../config/application', __FILE__)

module Rake
  class Task
    def invoke_with_appsignal(*args)
      Appsignal.listen_for_exception do
        invoke_without_appsignal(*args)
      end
    end

    alias_method_chain :invoke, :appsignal
  end
end

Rails.application.load_tasks
```

Any suggestions?

**Comment by thijsc** [comment]
That's actually pretty cool :-). I don't see real downsides to this, it might be a good idea to implement something like this in the gem. What do you think @matsimitsu?

**Comment by summerville** [comment]
Here's how Airbrake does it: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake_handler.rb

**Comment by tijmenb** [comment]
:+1:
