### ISSUE TITLE
Missing config causes exception in Appsignal::IPC.forked!, which kills all resque jobs

### ISSUE THREAD

**Issue by serioushaircut** [appsignal/appsignal#34]
Hi,
setup is rails 4.2 with resque integration. The problem is that we made a stupid small mistake and did not provide the configuration properly (with typo). Hence, for appsignal there wasn't any configuration. 

But the consequence turned out to be quite bad.
Appsignal::IPC.forked! tries to call stop_thread on Appsignal.agent, which is nil as it is only set when a config is present. That in turn stops the (all!) jobs from working/respawning at all with an exception.

I'd expected that we - naturally - wouldn't receive any signals, but that the job framework is killed is a rather harsh consequence :).

Cheers
SH

**Comment by matsimitsu** [comment]
Hi there,

We try to make sure AppSignal doesn't bring down the app when something is wrong with the gem itself, but as you unfortunately experienced there are some edge cases. 

I'll make sure we'll fix this in the next version, and will keep you updated.

Thanks for reporting!
