### ISSUE TITLE
Faraday request with middleware instrumentation enabled throws an error

### ISSUE THREAD

**Issue by rahilvirani** [appsignal/appsignal#36]
NoMethodError while sending queue: undefined method `each' for #<String:0x007f818a392b10>
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/middleware/delete_blanks.rb:6:in `call'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/middleware/chain.rb:81:in `block in invoke'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/middleware/chain.rb:84:in `call'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/middleware/chain.rb:84:in `invoke'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/post_processor.rb:13:in `block (2 levels) in post_processed_queue!'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/post_processor.rb:12:in `each'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/post_processor.rb:12:in `block in post_processed_queue!'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/post_processor.rb:11:in `map'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator/post_processor.rb:11:in `post_processed_queue!'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/aggregator.rb:42:in `post_processed_queue!'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/agent.rb:115:in `send_queue'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/agent.rb:42:in `block (2 levels) in start_thread'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/agent.rb:40:in `loop'
/Users/dev/.rvm/gems/ruby-2.2.0@influitive/gems/appsignal-0.11.8/lib/appsignal/agent.rb:40:in `block in start_thread'

Here is a code to make a http request using Faraday. if you have fa.use :instrumentation enabled, it will throw the above error.

         Faraday.new(options) do |fa|
            fa.use :instrumentation

            # Note the current Faraday (0.8.7) doesn't support options on retry (such as exceptions)
            # wait for the upgrade...
            fa.request :retry#, exceptions: [Faraday::Error::ConnectionFailed, Errno::ETIMEDOUT, Timeout::Error, Faraday::Error::TimeoutError]
            fa.request :url_encoded
            fa.request :json

            fa.response :json, content_type: /\bjson$/
            fa.adapter :net_http
          end

The payload is a string-ified Faraday object, whereas AppSignal expects the payload to a Hash

**Comment by thijsc** [comment]
Could you tell me what the payload of the event is in this case? If it's private e-mail is good too.

**Comment by rahilvirani** [comment]
#<Faraday::Env @method=:post @body="{\"token\":\"*******\"}" @url=#<URI::HTTP*******> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Accept"=>"application/json", "User-Agent"=>"Faraday v0.9.1", "Authorization"=>"Basic*******==", "Content-Length"=>"0"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x007fb76384aef0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"token"=>"******"} @url=#<URI::HTTP ********> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Accept"=>"application/json", "User-Agent"=>"Faraday v0.9.1", "Authorization"=>"Basic*******==", "Content-Length"=>"0"} @ssl=#<Faraday::SSLOptions (empty)> @response_headers={"x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "content-type"=>"application/json; charset=utf-8", "etag"=>"W/\"e5eaf6e5f234f1080ef3dcd39e57f8e4\"", "cache-control"=>"max-age=0, private, must-revalidate", "x-request-id"=>"60c6a22e-bb34-4a24-b468-6eff217a9748", "x-runtime"=>"0.016484", "server"=>"WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25)", "date"=>"Tue, 14 Apr 2015 18:41:06 GMT", "content-length"=>"52", "connection"=>"close"} @status=200>> @response_headers={"x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "content-type"=>"application/json; charset=utf-8", "etag"=>"W/\"e5eaf6e5f234f1080ef3dcd39e57f8e4\"", "cache-control"=>"max-age=0, private, must-revalidate", "x-request-id"=>"60c6a22e-bb34-4a24-b468-6eff217a9748", "x-runtime"=>"0.016484", "server"=>"WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25)", "date"=>"Tue, 14 Apr 2015 18:41:06 GMT", "content-length"=>"52", "connection"=>"close"} @status=200>

**Comment by thijsc** [comment]
Closing this one, we have a support thread running.
