### ISSUE TITLE
Don't send queue on shutdown if it's empty

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal#42]

**Comment by filipegiusti** [comment]
Awesome, thanks. I wrote [a workaround](https://github.com/DigitalArtists/appsignal/commit/903be782c695eb05be1cdee6e522194295338b22) just to keep my code working, would something like that with proper testing be accepted?

**Comment by thijsc** [comment]
I used your change and added some tests: 48d9fc248006e6247dfdf004874161a3bf3c0c51. This change will be in the next gem release we'll do this week.

Thanks!

**Comment by filipegiusti** [comment]
You're awesome! Thanks.
