### ISSUE TITLE
error with CLI `appsignal notify_of_deploy`

### ISSUE THREAD

**Issue by marciotrindade** [appsignal/appsignal#48]
Hi,

I'm using the `notify_of_deploy` to make a deploy on Appsignal, but when I try to make a deploy to `prod` enviroment it's create a new project with the same name but with 'pro' ENV.

Here the command line that I'm using:
```
appsignal notify_of_deploy --revision="038bbcc" --user="Marcio Trindade" --environment="prod" --name="Locaweb Backup"
```

The output is
```
I, [2015-07-16T17:05:36.624286 #53630]  INFO -- : Notifying Appsignal of deploy with: revision: 038bbcc, user: Marcio Trindade
I, [2015-07-16T17:05:38.027420 #53630]  INFO -- : Appsignal has been notified of this deploy!
```

and here the result at AppSignal

![appsignal](https://cloud.githubusercontent.com/assets/4888/8733989/4722737e-2bdd-11e5-81c1-b6035943cc04.png)

**Comment by matsimitsu** [comment]
Hi @marciotrindade Could you change `appsignal notify_of_deploy --revision="038bbcc" --user="Marcio Trindade" --environment="prod" --name="Locaweb Backup"` 

to : `appsignal notify_of_deploy --revision="038bbcc" --user="Marcio Trindade" --environment="production" --name="Locaweb Backup"` (the change is environment `prod` to `production`.

**Comment by marciotrindade** [comment]
Ops, now I understand, I used the env that appear in the AppSignal app instead the env that I configure.

Sorry for that and thank you for your help.

**Comment by matsimitsu** [comment]
No problem, glad I could help!
