### ISSUE TITLE
Capistrano integration breaks for latest 2.x release

### ISSUE THREAD

**Issue by clemens** [appsignal/appsignal#50]
The change introduced in https://github.com/capistrano/capistrano/commit/c971854ea7dc8ed26d9e858d57c203eccbb06d54 breaks your Capistrano 2 integration which expects `Capistrano::VERSION` to only be defined in Capistrano 3+.

I tried to write a failing test and fix the issue but failed with the test setup. The only insight I can provide is this: In the Capistrano runtime, the `capistrano/version` file is only loaded when invoking the help option via the CLI (see https://github.com/capistrano/capistrano/blob/legacy-v2/lib/capistrano/cli/options.rb#L118). So this constant is, in fact, never discovered. However, when I do my usual deploy call (`bundle exec cap production deploy`), for whichever reason it seems to be picked up.

To fix the issue, you probably need to require `capistrano/version` manually and adapt the version check something like the following: `if defined?(Capistrano::VERSION) && Gem::Version.new(Capistrano::VERSION) >= Gem::Version.new(3)`.

In the meantime, I've solved my issue by manually requiring the proper files:

``` ruby
# require 'appsignal/capistrano'
require 'appsignal'
require 'appsignal/integrations/capistrano/capistrano_2_tasks'
```
Hope this helps at least a little bit. :)

**Comment by matsimitsu** [comment]
Hi @clemens thanks for the info! I'll add this to the 0.11.13 release  :)

**Comment by matsimitsu** [comment]
Fixed in master :)
