### ISSUE TITLE
Transaction events array growth not limited - out of memory error

### ISSUE THREAD

**Issue by serioushaircut** [appsignal/appsignal#57]
Hi Appsignal,

setup Rails 4.2, Resque, Appsignal 0.11.11 - 
another problem we experienced with the Appsignal::Transaction class (see #56) is that it collects unbounded information about what is going on in the worker. 
We have a few jobs among hundreds that do quite a lot of statistical stuff over all users or articles etc, which reliably consume a lot of memory. The problem is that the jobs themselves do not have this massive memory footprint at all but the Appsignal instrumentation that gathers information about the jobs has.

We have to clear the Appsignal::Transaction events array from now and then in job itself. As stated in #56 even if we have enough memory for all events, we have to clear the events array anyway to avoid the DRbConnError caused by the drbunix load_limit in the referenced issue.

Cheers
Bastian

**Comment by matsimitsu** [comment]
Hi Bastian,

Thanks for the issue reports! This is unfortunately one of the few downsides of processing all instrumentation that Rails provides. 

We're working on a new version of the gem that handles this case a lot better. It's in beta right now, but could take a while before we release it. 

Meanwhile to prevent memory issues in long-running jobs we've implemented a way to "pause" the ingestion of instrumentation like so:

```ruby
class WorkWorker
  def perform
    Appsignal.without_instrumentation do
      # lots of heavy lifting here
    end
  end
end
```

This will still catch any errors that might occur, but it won't collect all the performance data. 

Let me know if this works for you right now. 

- Robert

**Comment by serioushaircut** [comment]
okay, much cleaner work around than clearing all events when the array gets too large.
we're looking forward to the new release. Yet this year possibly?
Cheers
Bastian
