### ISSUE TITLE
ActiveRecord query logging incomplete when using where("a='x' AND b='y'")

### ISSUE THREAD

**Issue by karsthammer** [appsignal/appsignal#93]
Hi guys,

When we make an ActiveRecord call in our application like:
`Post.where("created_at >= :timestamp AND updated_at >= :timestamp", timestamp: 1.day.ago)`

The query in AppSignal shows itself as:
```
SELECT `posts`.* FROM `posts` WHERE (created_at >= ?)
```

It seems that the SQL formatter uses regular expressions that are too eager (sql_formatter.rb, constants: SINGLE_QUOTED_STRING and DOUBLE_QUOTED_STRING). (see: http://rubular.com/r/CjFUo3v870)

Regard, Karst.

**Comment by thijsc** [comment]
Thanks for the detailed report! We're going to look into it and fix it.

**Comment by thijsc** [comment]
We've added a much improved Sql sanitizer in version `1.0.5`. This version is now in beta, could you give it a try?

```ruby
gem 'appsignal', '~> 1.0.5.beta'
```

**Comment by karsthammer** [comment]
Hi Thijs,

Just tested it and it works, it now logs the correct query in AppSignal.

Thanks!

**Comment by thijsc** [comment]
Awesome, thanks for testing!
