### ISSUE TITLE
Capistrano 3 integration should use `fetch(:stage)`

### ISSUE THREAD

**Issue by lucidstack** [appsignal/appsignal#94]
Hi there,

I'm trying out the `appsignal` gem, and while it works quite smoothly, I'm having an issue with capistrano deployments: appsignal always thinks I'm deploying to production, while I'm actually deploying to staging.

I think the culprit of this is at `lib/appsignal/integrations/capistrano/appsignal.cap:3` :
```
  1 namespace :appsignal do
  2   task :deploy do
  3     env = fetch(:rails_env, fetch(:rack_env, 'production')) #### <=
  4     user = ENV['USER'] || ENV['USERNAME']
  5     revision = fetch(:appsignal_revision, fetch(:current_revision))
```

Appsignal is using `:rails_env` or `:rack_env`, while it's pretty much standard to use `fetch(:stage)`. This will make appsignal use the right environment. Right now, if I `capistrano staging deploy`, a deploy appears in the production environment. By using `fetch(:stage)`, `staging` is used for deployment tracking, as I think it should be. :) 

Thanks a lot in advance!

**Comment by lucidstack** [comment]
Could I have some feedback on this, guys?

**Comment by thijsc** [comment]
This makes a lot of sense, we'll make this change. I expect we can do this for the next `1.2` release.

**Comment by lucidstack** [comment]
Thanks a lot, @thijsc! :+1:
